### ISSUE TITLE
Backend source code?

### ISSUE THREAD

**Issue by zmike808** [Talados/ClanTracker#3]
Are you planning to open source the backend code? Because otherwise this is just a plugin on the pluginhub for your personal use essentially.

**Comment by Talados** [comment]
I do not plan to open source the backend but I do plan on opening the registration for the public.

The plugin is currently on a test run for 3 clans, so far there were no bugs but I don't feel comfortable enough for an unlimited number of clans atm.

I hope you understand and feel free to reach out to me on discord and I'll add your clan aswell.
